#!/usr/bin/env python3
import sys,os,subprocess,json
def split_semicolons(file_contents):
    lines=file_contents.splitlines()
    sloc=[] # non-empty, comment-free lines
    for line in lines:
        line=line.strip()
        if '//' in line:
            start_of_comment=line.index('//')
            line=line[:start_of_comment]
            line=line.strip() # strip again to remove any spaces right before the comment
        for pref in line.split(';'):
            if len(pref)!=0: sloc.append(pref)
    return sloc
# if no name=value pairs specified, show a usage
if len(sys.argv)-1==0:
     print("Usage: python3 update_ffconfig.py (${NAME}=${VALUE})*")
     exit()
#parse the user.js file to get the current settings
oldpwd=os.getcwd()
# make sure it runs in the context of the utilities folder``
os.chdir(os.path.dirname(os.path.realpath(__file__)))
p=subprocess.Popen(f"node {os.path.dirname(__file__)}/../utilities/ffconfig_parse.js", shell=True, stdout=subprocess.PIPE, text=True)
if p.wait()!=0: raise ValueError("Parsing failed")
os.chdir(oldpwd)
setting_pairs=json.load(p.stdout)
setting_pairs=dict(zip(setting_pairs.keys(),map(lambda value:{"value":value,"type":type(value)},setting_pairs.values())))
#update the values as in the arguments
for update in sys.argv[1:]:
    name,value_json=update.split("=")
    value=json.loads(value_json)
    if name in setting_pairs:
        print(f"Updating {name} ({json.dumps(setting_pairs[name]['value'])} -> {value_json})")
    else:
        print(f"Adding {name}={value}")
    setting_pairs[name]={"value":value,"type":type(value)}
# wrap the pairs into user_pref("name",value) format
setting_lines_out=""
for name in setting_pairs:
    value=setting_pairs[name]["value"]
    typ=setting_pairs[name]["type"]
    setting_lines_out+=\
        f'user_pref(\"{name}\",'+json.dumps(typ(value))+');\n' # convert to the correct type before putting into json.dumps
#write the settings back to the file
with open(os.path.join(os.path.dirname(os.path.dirname(os.path.realpath(__file__))),"firefox-chrome","user.js"),'w') as settings_file:
    settings_file.write("// Generated by update_ffconfig.py, DO NOT EDIT\n")
    settings_file.write(setting_lines_out)

