#!/usr/bin/env python3
import sys,os,re,functools
def split_semicolons(file_contents):
    lines=file_contents.splitlines()
    sloc=[] # non-empty, comment-free lines
    for line in lines:
        line=line.strip()
        if '//' in line:
            start_of_comment=line.index('//')
            line=line[:start_of_comment]
            line=line.strip() # strip again to remove any spaces right before the comment
        for pref in line.split(';'):
            if len(pref)!=0: sloc.append(pref)
    return sloc
# if no name=value pairs specified, show a usage
if len(sys.argv)-1==0: print("Usage: ./update_ffconfig.py (${NAME}=${VALUE})*")
# read the current config
try:
    settings=open(os.path.join(os.path.dirname(os.path.dirname(os.path.realpath(__file__))),"firefox-chrome","user.js"))
except:
    settings=open(os.devnull)
setting_lines=list(\
    # remove any blank lines
    filter(lambda setting: len(setting)>0,\
        split_semicolons(settings.read())
    )
)
setting_lines_out=[]
settings.close()
setting_pairs={}
for setting in setting_lines:
    # parse the setting
    # remove all the wrapping and quotes
    # TODO: handle errors properly. Currently just ignores errorneous lines and treats them as if they weren't there
    if matches:=re.match(r'user_pref\("([A-Za-z\.]+)",(.+)\)$',setting):
       setting_pairs[matches.group(1)]=matches.group(2)
    else:
        raise ValueError("Parsing failed")
for update in sys.argv[1:]:
    name,value=update.split("=")
    if name in setting_pairs:
        print(f"Updating {name} ({setting_pairs[name]} -> {value})")
    else:
        print(f"Adding {name}={value}")
    setting_pairs[name]=value
for name in setting_pairs:
    value=setting_pairs[name]
    setting_lines_out.append(\
        f'user_pref(\"{name}\",{value})'
    )
#write the settings back to the file
settings=open(os.path.join(os.path.dirname(os.path.dirname(os.path.realpath(__file__))),"firefox-chrome","user.js"),'w')
settings.write("// Generated by update_ffconfig.py, DO NOT EDIT\n")
settings.write(\
    # use reduce to join with semicolons.
    # NOTE: We didn't use ';\n'.join(setting_lines) as that would cause the semicolon after the last setting to be missing
    functools.reduce(lambda a,b:a+b+';\n',setting_lines_out,'').strip()\
)

